FROM maven:3.8.6-amazoncorretto-19 AS build
COPY ./ /app
WORKDIR /app
RUN mvn --show-version --update-snapshots --batch-mode clean package

FROM amazoncorretto:18.0.2
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/target/customer-server-1.0-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java", "-jar", "customer-server-1.0-SNAPSHOT.jar"]